OCPNODE-1890: Bump k8s api to v0.29.0-alpha.3
openshift/apiserver-library-go pull request #125
Opened 2023-11-22 10:44 UTC by sairameshv

cc: @soltysh

2023-11-28 11:43 UTC, soltysh requested changes

2023-11-28 11:43 UTC, soltysh commented on go.mod
> +toolchain go1.21.4
Same as before, go1.20 and drop toolchain.

2023-11-29 15:55 UTC, sairameshv commented
/retest

2023-11-30 11:09 UTC, sairameshv commented
`go vet` is complaining about the newly introduced upstream [change](https://github.com/kubernetes/kubernetes/pull/120592/commits/070e7a38cb672b019ffbaf261da3b09f7feaeb01) in the `verify` job [failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_apiserver-library-go/125/pull-ci-openshift-apiserver-library-go-master-verify/1730172260079112192)

Error:
`vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go:228:42: cannot infer T (k8s.io/apimachinery@v0.29.0-rc.1/pkg/util/validation/field/errors.go:203:19)`

2023-12-18 14:46 UTC, soltysh approved these changes
/lgtm
/approve

2023-12-18 15:01 UTC, merged